# Generated by Django 4.2.7 on 2023-12-07 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofessionalpersonaldetails',
            name='UserIdFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
