# Generated by Django 4.2.7 on 2023-12-06 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('AppointmentIDPK', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Active', models.CharField(default='A')),
                ('BookingType', models.CharField(max_length=50)),
                ('AppointmentType', models.CharField(max_length=50)),
                ('AppointmentBy', models.CharField(max_length=50)),
                ('CenterType', models.CharField(max_length=50)),
                ('CreatedBy', models.CharField(max_length=8)),
                ('UpdatedBy', models.CharField(max_length=8)),
                ('CreationDateTime', models.DateTimeField(auto_now_add=True)),
                ('UpdationDateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MstPatient',
            fields=[
                ('RecordIDPK', models.AutoField(primary_key=True, serialize=False)),
                ('PatientID', models.CharField(max_length=11)),
                ('PatientProfileImage', models.ImageField(max_length=400, upload_to='')),
                ('FirstName', models.CharField(default=None, max_length=30)),
                ('MiddleName', models.CharField(default=None, max_length=30)),
                ('LastName', models.CharField(default=None, max_length=30)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'female'), ('O', 'Others')], max_length=9)),
                ('BloodGroup', models.CharField(default=None, max_length=4)),
                ('Nationality', models.CharField(default=None, max_length=15)),
                ('AadharNo', models.BigIntegerField(default=78)),
                ('MaritalStatus', models.CharField(choices=[('U', 'Unmarried'), ('Mrd', 'Married'), ('D', 'Divorcee'), ('W', 'Widow')], max_length=15)),
                ('Address', models.CharField(default=None, max_length=75)),
                ('City', models.CharField(default=None, max_length=25)),
                ('State', models.CharField(default=None, max_length=30)),
                ('Country', models.CharField(default=None, max_length=30)),
                ('Pin', models.IntegerField()),
                ('SpouseName', models.CharField(default=None, max_length=20)),
                ('DOB', models.DateField()),
                ('Age', models.IntegerField()),
                ('ActiveFlag', models.CharField(default=None, max_length=3)),
                ('CreatedBy', models.CharField(default='A', max_length=15)),
                ('UpdatedBy', models.CharField(default='A', max_length=15)),
                ('CreationDate', models.DateTimeField(auto_now_add=True)),
                ('UpdationDate', models.DateTimeField(auto_now=True)),
                ('UserIDFK', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MstPatientPaymentDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('PatientID', models.CharField(max_length=11)),
                ('PaymentType', models.CharField(default=None, max_length=15)),
                ('PaymentMode', models.CharField(blank=True, default='No mode', max_length=15)),
                ('InsuranceNo', models.CharField(default=None, max_length=20)),
                ('InsuranceCompanyName', models.CharField(default=None, max_length=100)),
                ('ActiveFlag', models.CharField(default=None, max_length=3)),
                ('CreatedBy', models.CharField(default='A', max_length=15)),
                ('UpdatedBy', models.CharField(default='A', max_length=15)),
                ('CreationDate', models.DateTimeField(auto_now_add=True)),
                ('UpdationDate', models.DateTimeField(auto_now=True)),
                ('RecordIDFK', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Patient.mstpatient')),
                ('UserIDFK', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MstPatientMedicalHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('PatientID', models.CharField(max_length=11)),
                ('PreExistingCondition', models.CharField(default=None, max_length=50)),
                ('Description', models.TextField()),
                ('MedicalRecordFile', models.URLField(max_length=400)),
                ('Remarks', models.CharField(default=None, max_length=40)),
                ('ActiveFlag', models.CharField(default=None, max_length=3)),
                ('CreatedBy', models.CharField(default='A', max_length=15)),
                ('UpdatedBy', models.CharField(default='A', max_length=15)),
                ('CreationDate', models.DateTimeField(auto_now_add=True)),
                ('UpdationDate', models.DateTimeField(auto_now=True)),
                ('RecordIDFK', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Patient.mstpatient')),
                ('UserIDFK', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MstPatientContact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('PatientID', models.CharField(max_length=11)),
                ('PatientContactNumber', models.BigIntegerField(default=None)),
                ('AlternatNumber', models.BigIntegerField(default=91)),
                ('PatientEmailId', models.EmailField(default=None, max_length=50)),
                ('EmergencyContactNumber', models.BigIntegerField()),
                ('EmergencyContactName', models.CharField(default=None, max_length=21)),
                ('EmergencyContactRelation', models.CharField(default=None, max_length=21)),
                ('ActiveFlag', models.CharField(default=None, max_length=3)),
                ('CreatedBy', models.CharField(default='A', max_length=15)),
                ('UpdatedBy', models.CharField(default='A', max_length=15)),
                ('CreationDate', models.DateTimeField(auto_now_add=True)),
                ('UpdationDate', models.DateTimeField(auto_now=True)),
                ('RecordIDFK', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Patient.mstpatient')),
                ('UserIDFK', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
