# Generated by Django 4.2.7 on 2023-12-06 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Staff', '0001_initial'),
        ('Patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='DoctorIDFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Staff.healthprofessionalpersonaldetails'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='PatientIDFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Patient.mstpatient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='SlotIDFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Staff.tbldoctorslot'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='UserIDFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
